set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

Plugin 'valloric/YouCompleteMe'
Plugin 'ervandew/supertab'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent off    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"

"Autoindent with tab being 2 spaces
set autoindent
set tabstop=2
set expandtab
set softtabstop=2 
"Numbers On
set number

"get highlighting
syntax on

"always show the tab line
set showtabline=2

"always show status line
set laststatus=2

"fold method
set foldmethod=marker
nnoremap <space> za

"bind F-Keys to move/manipulate tabs
map <F8> :tabprevious <CR>
map <F9> :tabnext <CR>
map <F5> :tabnew <CR>
map <F6> :tabmove - <CR>
map <F7> :tabmove + <CR>

colorscheme luna-term
let g:airline_theme='luna'
" DEFAULT THEMING CHANGES "
"fix highlighting with menu
"highlight Pmenu ctermfg=0 ctermbg=7 guifg=#000000 guibg=#F0F0F0
"Line number colors
"highlight LineNr ctermfg=3 ctermbg=0
"Tabline 
"highlight TabLineFill term=bold cterm=bold ctermbg=8 ctermfg=7
"Status line colors
"highlight StatusLine term=bold cterm=bold ctermbg=8 ctermfg=7
" let Vundle manage Vundle, required
"Plugin 'VundleVim/Vundle.vim'

